### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by samtygier**
Fix 2 warnings when run with PYTHONWARNINGS=d on python 3.7

### CODE REVIEW

**Comment by raveit65** [comment]
Or rebase against our master :)
This will remove the merged commit from PR.

**Comment by raveit65** [comment]
@flexiondotorg 
I think using the rebase+merge button here will exactly do what you requested.
You will see that if you run `git rebase master` in your local repo.

**Comment by samtygier** [comment]
I force pushed a new branch based on master, with just the 2 commits. Is that ok now?

**Comment by raveit65** [comment]
Looks OK https://github.com/mate-desktop/mozo/pull/58.patch

**Comment by raveit65** [comment]
Should be reviewed by another person because python isn't my workflow.

**Comment by yetist** [comment]
Patch is OK, but the PR shoud rebase on the master branch.

**Pull request merged**
